inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - lib/vcr_ws/actor_ws.rb
    - spec/spec_helper.rb